# Generated by Django 5.2.4 on 2025-07-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingrecord',
            old_name='exit_type',
            new_name='exit_time',
        ),
        migrations.AlterField(
            model_name='parkingrecord',
            name='parking_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_records', to='parking.parkinspot', verbose_name='Vaga'),
        ),
    ]
